### ISSUE TITLE
State of ARM NEON support

### ISSUE THREAD

**Issue by seeul8er** [catid/gf256#7]
Hi! Greate project 👍 
What is the current state of the ARM NEON support? What are the recommended compile options (set flags `GF256_TRY_NEON `or `HAVE_ARM_NEON_H`)?
I am interested in running it on the Raspberry Pi and only really need `gf256_mul_mem()` and `gf256_muladd_mem()`

**Comment by catid** [comment]
I'd add your architecture's define to this list in the header:

    #if defined(ANDROID) || defined(IOS) || defined(LINUX_ARM) || defined(__powerpc__) || defined(__s390__)
